- hosts: k8s
  remote_user: root
  tasks:
  - name: install-docker
    shell: apt install docker.io  apt-transport-https curl -y && systemctl enable docker && systemctl disable ufw && systemctl stop ufw && systemctl start docker
  - name: disable swap
    shell: swapoff -a 
  - name: change dns
    shell: echo "nameserver 185.51.200.2" > /etc/resolv.conf
    #  - name: gpg
    # shell: curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
  - name: install k8s
    shell: apt update && apt-get install kubeadm=1.20.4-00 kubelet=1.20.4-00 kubectl=1.20.4-00 -y && mkdir -p $HOME/.kube
  - name: add-apt-repo-kuber
    shell: echo "deb http://apt.kubernetes.io kubernetes-xenial main" > /etc/apt/sources.list.d/kubernetes.list
  - name: Disable SWAP in fstab 
    replace:
      path: /etc/fstab
      regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
      replace: '# \1'
